/* 
 * Author: Guy Soffer (gsoffer@yahoo.com)
 * Comments: GSOF July/12/2026
 * Revision history: 1
 */

#ifndef __SOLVER_6DOF_H
#define __SOLVER_6DOF_H

#include "mathLib.h"
#include "Vec_xyz.h"
#include "Vec_pqr.h"

/// Class members
struct sSolver_6DOF {
    const struct sMethods* method; //< Pointer to methods structure
	struct sPosition* pPosition;   //< Reference to read and update position vector
	struct sVec_xyz*  pVe;         //< Reference to read and update velocity vector in earth coordinates 
	struct sAttitude* pAttitude;   //< Reference to read and update attitude object
	struct sVec_pqr*  pWb;         //< Reference to read and update angular velocities vector
	float* I;                      //< Reference to read body inertia vector
	float* mass;                   //< Reference to read body mass 
};

/// Class methods
    struct sSolver_6DOF_methods {
	void (*__dtor__)(struct sSolver_6DOF*);

	void (*init)(
	  struct sSolver_6DOF*);
	  struct sPosition*,
      struct sVec_xyz*,
	  struct sAttitude*,
	  struct sVec_pqr*,
	  float*,
	  float*
	);
	
	struct sVec_xyz (*step)(
	  struct sSolver_6DOF*,
	  struct sVec_xyz*,
	  struct sVec_xyz*,
	  struct sVec_xyz*,
	  float
	);
};

/// Direct function declarations
/// Dynamically allocate memory for the object and initialize object members
sSolver_6DOF* S6dof__ctor__(
  struct sPosition* pPosition, //< Reference to read and update position vector
  struct sVec_xyz*  pVe,       //< Reference to read and update velocity in earth coordinates 
  struct sAttitude* pAttitude, //< Reference to read and update attitude
  struct sVec_pqr*  pWb,       //< Reference to read and update angular velocities
  float* pInertia,             //< Reference to read body inertia vector
  float* pMass                 //< Reference to read body mass 
);

/// Release the dynamicaly allocated memory of object
void* S6dof__dtor__(struct sSolver_6DOF* this);

/// Initialize the solver object
void S6dof_init(
  struct sSolver_6DOF* this,   //< Pointer to object
  struct sPosition* pPosition, //< Reference to read and update position vector
  struct sVec_xyz*  pVe,       //< Reference to read and update velocity in earth coordinates 
  struct sAttitude* pAttitude, //< Reference to read and update attitude
  struct sVec_pqr*  pWb,       //< Reference to read and update angular velocities
  float* pInertia,             //< Reference to read body inertia value
  float* pMass                 //< Reference to read body mass 
);

/// Step the solver
struct sVec_xyz S6dof_step(
  struct sSolver_6DOF* this, //< Pointer to object
  struct sVec_xyz*  pFext,   //< External forces
  struct sVec_xyz*  pFb,     //< Forces generated by forces 
  struct sVec_xyz*  pTb,     //< Torque generated by body
  float dt                   //< Calculation interval (seconds)
);

#endif
